sudo: required # required to use Docker inside TravisCI
language: generic

script:
  - docker build -f angular/Dockerfile.travis -t my-thai-star-angular .
  - docker build -f java/Dockerfile.travis -t my-thai-star-java .
