version: "3"

services:
  reverse-proxy:
    restart: always
    image: traefik:2.0.0
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    networks:
      - my-thai-star
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"

  java:
    build: "java/"
    restart: always
    image: my-thai-star/java:latest
    networks:
      - my-thai-star
    labels:
      - "traefik.http.routers.java.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.java.middlewares=fixpath"
      - "traefik.http.middlewares.fixpath.chain.middlewares=remove-api,add-mythaistar"
      - "traefik.http.middlewares.remove-api.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.add-mythaistar.addprefix.prefix=/mythaistar"
      - "traefik.http.services.java.loadBalancer.healthcheck.path=/mythaistar/services/rest/dishmanagement/v1/category/0/"
      - "traefik.http.services.java.loadBalancer.healthcheck.interval=10s"
      - "traefik.http.services.java.loadBalancer.healthcheck.scheme=http"
  angular:
    build: "angular/"
    restart: always
    image: my-thai-star/angular:latest
    networks:
      - my-thai-star
    labels:
      - "traefik.http.routers.angular.rule=PathPrefix(`/`)"
      - "traefik.http.services.angular.loadBalancer.healthcheck.path=/health"
      - "traefik.http.services.angular.loadBalancer.healthcheck.interval=10s"
      - "traefik.http.services.angular.loadBalancer.healthcheck.scheme=http"
networks:
  my-thai-star:
    driver: bridge
